export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <header>headaer</header>
      <body>{children}</body>
      <footer>footer</footer>
    </html>
  )
}
